# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A.ndim)
print(A.shape)
print(A.size)

2
(3, 5)
15


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
import numpy as np
 
# Define matrices B and C
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2
 
# Print matrices B and C
print("Matrix B:")
print(B)
print()
 
print("Matrix C:")
print(C)
 
# Elementwise subtraction
result_sub = B - C
print("\nElementwise Subtraction (B - C):")
print(result_sub)
 
# Elementwise multiplication
result_mul = B * C
print("\nElementwise Multiplication (B * C):")
print(result_mul)
 
# Matrix multiplication
result_matmul = B @ C
print("\nMatrix Multiplication (B @ C):")
print(result_matmul)
 

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise Subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
 import numpy as np
 
# Define matrix B
B = np.arange(1, 10).reshape(3, 3)
 
# Print matrix B
print("Matrix B:")
print(B)
 
# 1. Exponentiate each number elementwise
exp_B = np.exp(B)
print("\nExponentiation of each element (np.exp(B)):")
print(exp_B)
 
# 2. Minimum value in the whole matrix
min_value = np.min(B)
print("\nMinimum value in the whole matrix:")
print(min_value)
 
# 3. Minimum value in each row
min_per_row = np.min(B, axis=1)
print("\nMinimum value in each row:")
print(min_per_row)
 
# 4. Minimum value in each column
min_per_col = np.min(B, axis=0)
print("\nMinimum value in each column:")
print(min_per_col)
 
# 5. Index of the minimum value in the whole matrix
min_index = np.argmin(B)
print("\nIndex of the minimum value in the whole matrix:")
print(min_index)
 
# 6. Index of the minimum value in each row
min_index_per_row = np.argmin(B, axis=1)
print("\nIndex of the minimum value in each row:")
print(min_index_per_row)
 
# 7. Sum of all elements
sum_all_elements = np.sum(B)
print("\nSum of all elements:")
print(sum_all_elements)
 
# 8. Mean of each column
mean_per_col = np.mean(B, axis=0)
print("\nMean of each column:")
print(mean_per_col)
 
# 9. Median of each column
median_per_col = np.median(B, axis=0)
print("\nMedian of each column:")
print(median_per_col)
 
 

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiation of each element (np.exp(B)):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix:
1

Minimum value in each row:
[1 4 7]

Minimum value in each column:
[1 2 3]

Index of the minimum value in the whole matrix:
0

Index of the minimum value in each row:
[0 0 0]

Sum of all elements:
45

Mean of each column:
[4. 5. 6.]

Median of each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

det visar rad two

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [16]:
for i in A:
    for element in i:
        print(element)
    print("färdig")
 

1
2
3
4
5
färdig
6
7
8
9
10
färdig
11
12
13
14
15
färdig


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [17]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# siffra 2 är block, 3 är row -1 är valfritt 

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)